# name: kltheguide
# description: A new Flutter project.

# # The following line prevents the package from being accidentally published to
# # pub.dev using `pub publish`. This is preferred for private packages.
# publish_to: "none" # Remove this line if you wish to publish to pub.dev

# # The following defines the version and build number for your application.
# # A version number is three numbers separated by dots, like 1.2.43
# # followed by an optional build number separated by a +.
# # Both the version and the builder number may be overridden in flutter
# # build by specifying --build-name and --build-number, respectively.
# # In Android, build-name is used as versionName while build-number used as versionCode.
# # Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# # In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# # Read more about iOS versioning at
# # https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# version: 1.5.0+69

# environment:
#   sdk: ">=3.1.0 <4.0.0"
#   flutter: ">=3.10.0"

# dependencies:
#   flutter:
#     sdk: flutter
#   flutter_native_splash: ^2.4.6
#   win32: ^5.14.0
#   cupertino_icons: ^1.0.8
#   carousel_slider: ^5.1.1
#   http: ^1.4.0
#   cached_network_image: ^3.4.1
#   flutter_cache_manager: ^3.4.1
#   intl: ^0.20.2 # Required for Flutter Intl
#   html: ^0.15.6
#   flutter_html: ^3.0.0-beta.2
#   flutter_inappwebview: ^6.1.5
#   shared_preferences: ^2.5.3
#   flutter_pdfview: ^1.4.1+1
#   flutter_cached_pdfview: ^0.4.3
#   flutter_downloader: ^1.12.0
#   path_provider: ^2.1.5
#   google_mobile_ads: ^6.0.0
#   url_launcher: ^6.3.1
#   permission_handler: ^12.0.1
#   vibration: ^3.1.3
#   font_awesome_flutter: ^10.8.0
#   package_info_plus: ^8.3.0
#   archive: ^4.0.7
#   flutter_localizations: # Required for Flutter Intl
#     sdk: flutter
#   in_app_update: ^4.2.3

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_launcher_icons: ^0.14.4
#   intl_utils: ^2.8.11 # Flutter Intl utility for generating localization files


# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/android-chrome-512x512.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21

# # For information on the generic Dart part of this file, see the
# # following page: https://dart.dev/tools/pub/pubspec

# # The following section is specific to Flutter.
# flutter:
#   # The following line ensures that the Material Icons font is
#   # included with your application, so that you can use the icons in
#   # the material Icons class.
#   uses-material-design: true

#   # To add assets to your application, add an assets section, like this:
#   assets:
#     #articles
#     - assets/images/
#     - assets/images/contentList/historicalPlaces/5.jpg

#   fonts:
#     - family: MyFlutterApp
#       fonts:
#         - asset: assets/fonts/MyFlutterApp.ttf

#   # An image asset can refer to one or more resolution-specific "variants", see
#   # https://flutter.dev/assets-and-images/#resolution-aware.

#   # For details regarding adding assets from package dependencies, see
#   # https://flutter.dev/assets-and-images/#from-packages

#   # To add custom fonts to your application, add a fonts section here,
#   # in this "flutter" section. Each entry in this list should have a
#   # "family" key with the font family name, and a "fonts" key with a
#   # list giving the asset and other descriptors for the font. For
#   # example:

#   #   - family: Trajan Pro
#   #     fonts:
#   #       - asset: fonts/TrajanPro.ttf
#   #       - asset: fonts/TrajanPro_Bold.ttf
#   #         weight: 700
#   #
#   # For details regarding fonts from package dependencies,
#   # see https://flutter.dev/custom-fonts/#from-packages


name: kltheguide
description: A new Flutter project.
publish_to: "none"

version: 1.5.0+69

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  win32: ^5.14.0
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  http: ^1.4.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  intl: ^0.20.2
  html: ^0.15.6
  flutter_html: ^3.0.0-beta.2
  flutter_inappwebview: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_pdfview: ^1.4.1+1
  flutter_cached_pdfview: ^0.4.3
  flutter_downloader: ^1.12.0
  path_provider: ^2.1.5
  google_mobile_ads: ^6.0.0
  url_launcher: ^6.3.1
  permission_handler: ^12.0.1
  vibration: ^3.1.3
  font_awesome_flutter: ^10.8.0
  package_info_plus: ^8.3.0
  archive: ^4.0.7
  flutter_localizations:
    sdk: flutter
  in_app_update: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  intl_utils: ^2.8.11

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/android-chrome-512x512.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/contentList/historicalPlaces/5.jpg
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf



